### ISSUE TITLE
Auto update issue

### ISSUE THREAD

**Issue by dakman** [marcusig/woocommerce-product-customizer#74]
Auto updates dont appear to be working after WP 6.3 release

![image](https://github.com/marcusig/woocommerce-product-customizer/assets/2136346/4b562923-b3fa-4d96-ad71-427078171d51)
![image](https://github.com/marcusig/woocommerce-product-customizer/assets/2136346/3cef0e85-13d5-4d3c-bbf2-d21310abf9ce)

**Comment by marcusig** [comment]
The update notice shows the message "Automatic update is unavailable for this plugin".
This is usually either because you haven't connected the license, or the license has expired.

**Comment by dakman** [comment]
![image](https://github.com/marcusig/woocommerce-product-customizer/assets/2136346/a7451b15-9a6b-4ae7-bb5e-b5757f4bbe54)


this is what we see and the license is active.. the client just renewed it

**Comment by marcusig** [comment]
Is manual update available?
This is what it should look like: 

![image](https://github.com/marcusig/woocommerce-product-customizer/assets/11990914/7ac8d9be-21cf-4ad9-a9aa-ca10694555f7)

If the manual update isn't available either, please use the [premium support form](https://wc-product-configurator.com/my-account/support/) so that I see which account it is. 
Maybe there is an issue with the license.

If your client only just renewed (within the past 24h), you may need to press the "check for updates" link, or visit the `wp-admin/update-core.php` page, which forces update checks and will check the license again.

**Comment by dakman** [comment]
i forwarded the email with the receipt from July 7th .. thanks and great work on the plugin :)

**Comment by dakman** [comment]
i also just tried going to that wp-admin/update-core.php url after being logged in and it still shows the warning messages .. should I try purging configurator cache? thx again

**Comment by dakman** [comment]
perfect i think you addressed the issue.. our mistake! have a great day! closing the issue.

**Comment by marcusig** [comment]
Thanks! 
Then you can just use the disconnect button, and reconnect with the same credentials, and it should work again.

**Comment by dakman** [comment]
Ok I will let the client know .. I don't believe I have the credentials
saved :/
