### ISSUE TITLE
Add to cart button not working

### ISSUE THREAD

**Issue by Kiscsoszi** [marcusig/woocommerce-product-customizer#85]
This product page: [Product](https://gravix.hu/termek/egyedi-ajandek/)

I can't put it in the cart in the editor.

However, if I close it and click on the basic add to cart option, the configured product is added to the cart.

**Comment by marcusig** [comment]
Hi there, 

There could be a conflict with an other plugin.
Though it is difficult to say because the JavaScript is minified and it could be just that the issue.
I would recommend deactivating "Jetpack Boost" to see if that solves the issue. 

Marc

PS: If you wouldn't mind in the future using [the support forum here](https://wordpress.org/support/plugin/product-configurator-for-woocommerce/), as github issues are more for identified bugs, not general help questions.

**Comment by Kiscsoszi** [comment]
Thank you very much!
You solved the problem!

Okay, I understood. I hope it doesn't happen next time. :)

**Comment by Kiscsoszi** [comment]
Thanks Marc!
